### ISSUE TITLE
Typescript unable to compile

### ISSUE THREAD

**Issue by rescoluis** [shiwano/typhen#11]
I was trying to compile a simple interface but got this error:

Fatal Error: Failed to read the file: fileName: .../AppData/Roaming/npm/node_modules/typhen/node_modules/typescript/lib/@@__typhen.lib.d.ts

I'm using TS 2.2.2

**Comment by studds** [comment]
I'm getting the same error, on windows only. Works fine on osx/linux.

```
11:57:57.546 Parsing TypeScript files
11:57:57.608 Fatal Error: Failed to read the file: fileName: C:/go-agents/agent1/pipelines/threads-interfaces/node_modules/typhen/node_modules/typescript/lib/@@__typhen.lib.d.ts Error: Error: ENOENT: no such file or directory, open 'C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\node_modules\typescript\lib\@@__typhen.lib.d.ts'
11:57:57.608     at CompilerHost.getSourceFile (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\lib\compiler_host.js:18:23)
11:57:57.608     at findSourceFile (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\node_modules\typescript\lib\typescript.js:64751:29)
11:57:57.608     at processSourceFile (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\node_modules\typescript\lib\typescript.js:64682:27)
11:57:57.608     at processRootFile (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\node_modules\typescript\lib\typescript.js:64570:13)
11:57:57.608     at Object.createProgram (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\node_modules\typescript\lib\typescript.js:63939:21)
11:57:57.608     at TypeScriptParser.parse (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\lib\typescript_parser.js:61:27)
11:57:57.608     at C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\lib\runner.js:32:20
11:57:57.608     at Promise._execute (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\bluebird\js\release\debuggability.js:313:9)
11:57:57.608     at Promise._resolveFromExecutor (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\bluebird\js\release\promise.js:483:18)
11:57:57.608     at new Promise (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\bluebird\js\release\promise.js:79:10)
11:57:57.608     at Runner.run (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\lib\runner.js:29:16)
11:57:57.608     at Object.run (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\lib\index.js:19:49)
11:57:57.608     at Object.<anonymous> (C:\go-agents\agent1\pipelines\threads-interfaces\node_modules\typhen\bin\typhen:86:12)
11:57:57.608     at Module._compile (module.js:570:32)
11:57:57.608     at Object.Module._extensions..js (module.js:579:10)
11:57:57.608     at Module.load (module.js:487:32)
```

**Comment by skorunka** [comment]
Having the same issue
